-- MySQL Script generated by MySQL Workbench
-- Sun Jun  5 17:07:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eof19
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eof19` ;

-- -----------------------------------------------------
-- Schema eof19
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eof19` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `eof19` ;

-- -----------------------------------------------------
-- Table `eof19`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eof19`.`petstore` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eof19`.`petstore` (
  `pst_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(30) NOT NULL,
  `pst_street` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` CHAR(9) NOT NULL,
  `pst_phone` BIGINT UNSIGNED NOT NULL,
  `pst_email` VARCHAR(100) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_ytd_sales` DECIMAL(10,2) NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eof19`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eof19`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eof19`.`customer` (
  `cus_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(15) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_city` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` CHAR(9) NOT NULL,
  `cus_phone` BIGINT UNSIGNED NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_balance` DECIMAL(8,2) NOT NULL,
  `cus_total_sales` DECIMAL(8,2) NOT NULL,
  `cus_notes` VARCHAR(45) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eof19`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eof19`.`pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eof19`.`pet` (
  `pet_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_id` SMALLINT UNSIGNED NOT NULL,
  `cus_id` SMALLINT UNSIGNED NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `pet_sex` ENUM('m', 'f') NOT NULL,
  `pet_cost` DECIMAL(6,2) NOT NULL COMMENT 'pet store’s cost ',
  `pet_price` DECIMAL(6,2) NOT NULL,
  `pet_age` TINYINT NOT NULL,
  `pet_color` VARCHAR(30) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y', 'n') NOT NULL,
  `pet_neuter` ENUM('y', 'n') NOT NULL,
  `pet_notes` VARCHAR(225) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_pet_customer_idx` (`cus_id` ASC) VISIBLE,
  INDEX `fk_pet_petstore1_idx` (`pst_id` ASC) VISIBLE,
  CONSTRAINT `fk_pet_customer`
    FOREIGN KEY (`cus_id`)
    REFERENCES `eof19`.`customer` (`cus_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pet_petstore1`
    FOREIGN KEY (`pst_id`)
    REFERENCES `eof19`.`petstore` (`pst_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `eof19`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `eof19`;
INSERT INTO `eof19`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Sun', '1700 Directors Row', 'Orlando', 'FL', '328097654', 3742933448, 'saveuspets@gmail.com', 'https://www.saveuspets.com', 50000, 'notes1');
INSERT INTO `eof19`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Bick', '123 Main St.', 'L.A.', 'CA', '902459835', 9097689876, 'cooldogs@gmail.com', 'https://www.cooldogs.com', 70000, 'notes2');
INSERT INTO `eof19`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Rex', '1309 E 13th St', 'Austin', 'TX', '787025427', 3940867648, 'coolpets@yahoo.com', 'https://www.coolpets.com', 84000, 'notes3');
INSERT INTO `eof19`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Red', '5608 W Washington Blvd', 'Chicago', 'IL', '606449475', 8765467321, 'coolcats@gmail.com', 'https://www.coolcats.com', 60000, 'notes4');
INSERT INTO `eof19`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Bigboy', '7753 1st Ave S', 'Birmingham', 'AL', '352066375', 5513849476, 'bestpets@hotmail.com', 'https://www.bestpets.com', 39000, 'notes5');
INSERT INTO `eof19`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Light', '2153 NW 3rd St', 'Miami ', 'FL', '331258225', 5619878976, 'ineedahome@gmail.com', 'https://www.ineedahome.com', 87000, 'notes6');
INSERT INTO `eof19`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Grim', '1300 17th St', 'Rockford', 'IL', '611044456', 8742633748, 'catsanddogs@aol.com', 'https://www.catsanddogs.com', 89000, 'notes7');
INSERT INTO `eof19`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Will', '725 Carver Ave', 'Auburn', 'AL', '368328865', 3513843475, 'furrypetsneed@yahoo.com', 'https://www.furrypetsneed.com', 66000, 'notes8');
INSERT INTO `eof19`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Rubby', '811 4th St.', 'NY', 'NY', '100129445', 9873274326, 'doglover@hotmail.com', 'https://www.doglover.com', 49000, 'notes9');
INSERT INTO `eof19`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Luck', '620 McLaws St', 'Savannah', 'GA', '314054776', 4658732563, 'furryguys@gmail.com', 'https://www.furryguys.com', 90000, 'notes10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eof19`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `eof19`;
INSERT INTO `eof19`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Sam', 'Ray', '1809 Romeria Dr', 'Dallas', 'TX', '787577639', 6789345274, 'samcool@gmail.com', 104.34, 1000.34, 'notes1');
INSERT INTO `eof19`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Enoch', 'Jean', '560 Mandalay Rd', 'Jacksonville', 'FL', '322167654', 5628983456, 'enochjean@hotmail.com', 89.43, 257.97, 'notes2');
INSERT INTO `eof19`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Mark', 'Tim', '1412 Russell St', 'Tallahassee', 'FL', '323657865', 3274356789, 'marktim@fsu.edu', 33.67, 463.98, 'notes3');
INSERT INTO `eof19`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Bob', 'Key', '1399 NW 29th Terrace', 'Miami', 'FL', '323456645', 2450937854, 'bobk@gmail.com', 50.35, 854.56, 'notes4');
INSERT INTO `eof19`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Mark', 'Faulknor ', '1301 Blair St', 'Houston', 'TX', '770085437', 4372851894, 'jaynick@hotmail.com', 136.98, 1992.99, 'notes5');
INSERT INTO `eof19`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Jay', 'Nick', '502 Shady Dr', 'Minneapolis', 'MN', '401147636', 5437847676, 'rfloor@aol.com', 78.35, 203.45, 'notes6');
INSERT INTO `eof19`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Ray', 'Floor', '268 7th St', 'Buffalo', 'NY', '142014356', 2354674334, 'rayfloor@gmail.com', 20.35, 425.95, 'notes7');
INSERT INTO `eof19`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Stevie', 'Top', '8624 Baldwin Dr', 'Panama City Beach ', 'FL', '474583275', 2843754673, 'topstevie@fsu.edu', 33.24, 804.99, 'notes8');
INSERT INTO `eof19`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Fin', 'Pool', '4198 23rd St', 'San Francisco', 'CA', '941149842', 4753845904, 'poolfin@gmail.com', 89.94, 845.43, 'notes9');
INSERT INTO `eof19`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Paul', 'Simp', '63178 Northshore Dr', 'Laramin', 'WY', '473892734', 7563452853, 'simppaul@hotmail.com', 2.0, 289.93, 'notes10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eof19`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `eof19`;
INSERT INTO `eof19`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, 5, 'Doberman', 'm', 300, 525, 52, 'black/tan ', '2009-07-05', 'y', 'y', 'notes1');
INSERT INTO `eof19`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 7, 1, 'Chiwawa', 'm', 175, 165, 78, 'white/brown', NULL, 'n', 'n', 'notes2');
INSERT INTO `eof19`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 3, 2, 'American Bobtail', 'f', 195, 385, 104, 'black ', '2011-12-24', 'y', 'y', 'notes3');
INSERT INTO `eof19`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 2, 4, 'American Longhair', 'm', 165, 275, 103, 'white', '2005-08-01', 'n', 'y', 'notes4');
INSERT INTO `eof19`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 5, 9, 'British Shorthair ', 'f', 155, 145, 28, 'grey', NULL, 'y', 'n', 'notes5');
INSERT INTO `eof19`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, 6, 'Rose-Ringed Parakeet', 'f', 18, 32, 2, 'green/yellow', '2010-11-12', 'n', 'n', 'notes6');
INSERT INTO `eof19`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 7, 8, 'African Grey Parrot', 'm', 1295, 1800, 105, 'grey/blue', '2007-09-19', 'n', 'n', 'approx. 10 yrs old');
INSERT INTO `eof19`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 5, 8, 'Pitbull', 'f', 300, 495, 8, 'black/white', '2001-05-27', 'n', 'y', 'notes8');
INSERT INTO `eof19`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 9, 7, 'Boa Constrictor', 'm', 450, 735, 80, 'grey/green', '2006-10-31', 'n', 'n', 'approx. 5 yrs old');
INSERT INTO `eof19`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 10, 1, 'Giraffe', 'f', 1735, 2495, 100, 'yellow and black', NULL, 'n', 'n', 'notes10');

COMMIT;

